### ISSUE TITLE
react-redux v7.1.0 SSR hooks connectAdvanced.js

### ISSUE THREAD

**Issue by maximandrews** [reduxjs/react-redux#1362]
**Do you want to request a _feature_ or report a _bug_?**
Bug report
**What is the current behavior?**
It works well in a browser.

When I use react-redux@7.1.0 with SSR, every time ReactDOMServer.renderToString called (browser refresh cmd + R on mac for chrome) it throws the error in a terminal:
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at invariant (/Users/maxim/setup-app-suite/packages/setup-app-templates/templates/react-redux-thunk-router/node_modules/react/cjs/react.development.js:85:0)
    at resolveDispatcher (/Users/maxim/setup-app-suite/packages/setup-app-templates/templates/react-redux-thunk-router/node_modules/react/cjs/react.development.js:1470:0)
    at useMemo (/Users/maxim/setup-app-suite/packages/setup-app-templates/templates/react-redux-thunk-router/node_modules/react/cjs/react.development.js:1524:0)
    at ConnectFunction (/Users/maxim/setup-app-suite/packages/setup-app-templates/templates/react-redux-thunk-router/node_modules/react-redux/es/components/connectAdvanced.js:116:28)
    at processChild (/Users/maxim/setup-app-suite/packages/setup-app-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:2888:14)
    at resolve (/Users/maxim/setup-app-suite/packages/setup-app-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Users/maxim/setup-app-suite/packages/setup-app-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/Users/maxim/setup-app-suite/packages/setup-app-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at Object.renderToString (/Users/maxim/setup-app-suite/packages/setup-app-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at processMethod (/Users/maxim/setup-app-suite/packages/setup-app-ssr/lib/SSRMiddleware.js:70:41)
```
Also, if you do view source (don't be confused with inspect) in a browser there will be no pre-rendered HTML.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:**
Because it is SSR I don't have "minimal demo".

You should have lerna installed globally:
`nmp i lerna -g`

1. `git clone git@github.com:maxim-andrews/setup-app-suite.git`
2. `cd setup-app-suite/packages/setup-app-templates/templates/react-redux-thunk-router`
3. `npm i && npm i react-redux@7.1.0`
4. for better debugging `npm link ../../../fullstack-scripts && npm link ../../../setup-app-ssr && lerna bootstrap`
5. `npm start`

See output in the terminal (do not confuse with chrome DevTools console).

Every time you will refresh a browser it will call ReactDOMServer.renderToString and will produce the error above to the terminal.

1. Versions are matching: react@16.8.6 and react-dom@16.8.6
3. There is only one copy of react & react-dom

I believe the problem occurs because it's calling `useMemo` not in a functional component body.

> 2. You might be breaking the Rules of Hooks

See the stack above. The `resolveDispatcher` checks what is current functional component and then throws the error.

I believe issue starts [here](https://github.com/reduxjs/react-redux/blob/dcf2cb0864fffa58d914146cd08f2402ef66b1a9/src/components/connectAdvanced.js#L163)

**What is the expected behavior?**
There should be no error and react should render to HTML.

If you will run `npm i react-redux@6.0.1` everything will work fine.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**
```
react@16.8.6
react-dom@16.8.6
react-redux@7.1.0
react-router@5.0.1
react-router-dom@5.0.1
redux@4.0.4
redux-thunk@2.3.0
```
In a browser works fine, just SSR.

It works well with `react-redux@6.0.1`

Run `npm i react-redux@6.0.1` to see expected behavior.

**Comment by markerikson** [comment]
Please check to make sure that not only are the versions matching in `package.json`, that you absolutely do not have any other versions of React / ReactDOM installed anywhere in your `node_modules`.

We know that this version works okay in an SSR environment, so the issue is likely due to your build setup or local version somehow.

**Comment by maximandrews** [comment]
@markerikson there is no any "multi-workspace" setup.

If you will do `npm ls react` or `npm ls react-dom` you will see there is only one version installed.

> We know that this version works okay in an SSR environment
 
Please, could you provide any repo with working example?

**Comment by dinfyru** [comment]
I have the same error with `react-redux` 7.1.0

**Comment by maximandrews** [comment]
Hey @dinfyru I have some workaround for this issue.

You can find the actual solution [here](https://medium.com/@MaximAndrews/invalid-hook-call-issue-solved-when-configuring-with-lerna-ssr-and-react-redux-v7-1-0-408878740ffe).
