### ISSUE TITLE
SSR render of SystemJS stop working with version 7.1.1

### ISSUE THREAD

**Issue by grvpanchal** [reduxjs/react-redux#1787]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 16.14.0
- ReactDOM/React Native: 16.14.0
- Redux: 3.7.2
- React Redux: 7.1.1
- SystemJS: 6.10.2

I have code in https://github.com/grvpanchal/react-redux-app-ypsn1g/tree/react-redux-711-not-working

just
```sh
npm install
npm run build
npm run start:ssr
```

For server-side rendering I have following
```js
const fs = require('fs')
const express = require('express')
const React = require('react');
const url = require('url');
const SystemJS = require('systemjs');
const { Provider } = require('react-redux');
const { renderToString } = require('react-dom/server');

const importMap = require('./public/importmap.json');

global.System = SystemJS.System;
const { applyImportMap, setBaseUrl } = SystemJS;

const basePath = url.pathToFileURL(process.cwd()).href;
setBaseUrl(global.System, basePath);

applyImportMap(global.System, importMap);


const app = express()
app.use(express.static('build', {
    index: false
}))
const port = 3000

app.use(express.static('build', {
    index: false
}))

const indexHTML = fs.readFileSync('./public/index.html',{ encoding:'utf8', flag:'r'});

app.get('/', async (req, res) => {
    const AppJs = await global.System.import('@mfe/app');
    const AppEle = React.createElement(AppJs.default);
    const ReduxProvider = React.createElement(Provider, { store: AppJs.store }, AppEle);
    const outputReactDom = renderToString(ReduxProvider);
    const outputHTML = indexHTML
        .replace(
            /(<div id="root"><\/div>)/igm,
            `
            <div id="root">
                ${outputReactDom}
            </div>
            <script type="systemjs-module" src="/static/js/main.system.js"></script>
        `);
    
  res.send(outputHTML)
})

app.listen(port, () => {
  console.log(`SystemJS SSR app listening at http://localhost:${port}`)
})
```

### What is the current behavior?

I get the following error for 7.1.1
```
SystemJS SSR app listening at http://localhost:3000
(node:8144) UnhandledPromiseRejectionWarning: Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (https://cdn.jsdelivr.net/npm/@esm-bundle/react@16.14.0/system/react.development.js:1659:16)
    at useMemo (https://cdn.jsdelivr.net/npm/@esm-bundle/react@16.14.0/system/react.development.js:1714:23)
    at ConnectFunction (http://localhost:3000/static/js/mfe-app.system.js:1801:56)
    at processChild (C:\Users\HOME\Documents\projects\react-redux-app-ypsn1g\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)        
    at resolve (C:\Users\HOME\Documents\projects\react-redux-app-ypsn1g\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (C:\Users\HOME\Documents\projects\react-redux-app-ypsn1g\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (C:\Users\HOME\Documents\projects\react-redux-app-ypsn1g\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToString (C:\Users\HOME\Documents\projects\react-redux-app-ypsn1g\node_modules\react-dom\cjs\react-dom-server.node.development.js:3988:27)      
    at C:\Users\HOME\Documents\projects\react-redux-app-ypsn1g\server.js:36:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate 
the Node.js process with a non-zero exit code.
```

### What is the expected behavior?

```js
const outputReactDom = renderToString(ReduxProvider);
```

The above code should output HTML as a string but the app craches. it works fine with 5.0.7

### Which browser and OS are affected by this issue?

nodejs

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by markerikson** [comment]
I can tell you that v5 and v6 did not use hooks, while v7 does. So, it's likely you have some kind of a build misconfiguration that breaks when hooks are used at all, and this is not actually a React-Redux problem - it's a React problem.  

This is typically due to multiple copies of React being loaded at the same time.

**Comment by grvpanchal** [comment]
I tried with and without the external import of React and ReactDOM but the error still remains when `targetLibrary: 'system'` is used in webpack.config.js.

**Comment by markerikson** [comment]
Just for comparison: what happens if you write any tiny React component that uses a hook such as `useState` and try to SSR that, but without any React-Redux used in the tree at all?  Do you still get that error?

**Comment by grvpanchal** [comment]
Ok I shall try and get back

**Comment by grvpanchal** [comment]
I pushed the changes. I was able to fix it by sending the provider to the package. When the Provider was created from the server-side, the context of the provider was not passed which caused the issue. Also, the ReactDOM was loaded twice so I did the following
```js
    const AppJs = await global.System.import('@mfe/app');
    const { default: React } = await global.System.import('react');
    const { renderToString } = await global.System.import('react-dom/server');
    const AppElement = React.createElement(AppJs.default, { store });
    const outputReactDom = renderToString(AppElement);
```
