### ISSUE TITLE
TypeError: dispatcher.useSyncExternalStore is not a function

### ISSUE THREAD

**Issue by Raghav-254** [reduxjs/react-redux#2108]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM: 18.2.0
- Redux Toolkit: 2.0.1
- React Redux: 9.0.4

### What is the current behavior?

Recently came to know that react-redux is now officially providing the support of React 18 but on upgrading the version of react-redux from 8.1.3 to 9.0.4, I am receiving this error **dispatcher.useSyncExternalStore is not a function**

Full error:
react.development.js:1676 Uncaught (in promise) TypeError: dispatcher.useSyncExternalStore is not a function
    at useSyncExternalStore (react.development.js:1676:1)
    at ConnectFunction (react-redux.mjs:963:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at updateSimpleMemoComponent (react-dom.development.js:17215:1)
    at updateMemoComponent (react-dom.development.js:17092:1)
    at beginWork (react-dom.development.js:19135:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)

Can you please check what could be the issue?

### What is the expected behavior?

Ideally this error should not come up.

### Which browser and OS are affected by this issue?

Google Chrome

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by phryneas** [comment]
That sounds like for some reason you have multiple different `react` or `react-dom` versions installed in your project. You can check that with `npm ls react`/`npm ls react-dom`/`yarn why react`/`yarn why react-dom`.
