### ISSUE TITLE
`connect` throws `TypeError: Cannot call a class as a function` in normal usage

### ISSUE THREAD

**Issue by cyan33** [reduxjs/react-redux#963]
Why this test case is throwing the error below?

```js
it('shouldn\'t throw error', () => {
  expect(connect(state => state)(
    class Foo extends Component {
      render() {
        return <div />
      }
    }
  )).not.toThrow()
})
```

Error:

```js
React › connect › shouldn't throw error

    expect(function).not.toThrow()

    Expected the function not to throw an error.
    Instead, it threw:
      TypeError: Cannot call a class as a function


          at _classCallCheck (src/components/connectAdvanced.js:5264:99)
          at Connect (src/components/connectAdvanced.js:122:35)
          at Object.<anonymous> (node_modules/expect/build/to_throw_matchers.js:42:7)
          at Object.throwingMatcher [as toThrow] (node_modules/expect/build/index.js:147:24)
          at Object.<anonymous> (test/components/connect.spec.js:1224:14)

```

Also, why are there 12 failing test cases when I run `yarn test` at first place? Am I missing anything?

**Comment by timdorr** [comment]
You can't just put the class inside `connect`. This will work:
```js
it("shouldn't throw an error", () => {
  class Foo extends Component {
    render() {
      return <div />
    }
  }
  expect(connect(state => state)(Foo)).not.toThrow()
})
```

**Comment by cyan33** [comment]
@timdorr No offense but this doesn't work either. Throws the same error.
